### PR TITLE
Add unit test for saving a new file

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
ping?

Can you please publish a new version with the fix? Thanks.

**Comment by orgads** [comment]
Please publish a new version

**Comment by dbrady** [comment]
Thank you for the reminder! I lost track of this. Version 0.1.4 is published. Developers will need to `bundle install` and possibly `bundle upgrade`.

**Comment by orgads** [comment]
Thank you. Please add a tag in git.

**Pull request merged**
