### PR TITLE
Usage as a Library Improvements

### PR DESCRIPTION
**Pull request by dkowis**
I'm wanting to use this as a library, and I'd like to be able to specify the file path. Super easy change that doesn't make any existing stuff wrong or broken, but lets me initialize the `ConfigFile` with a different path, say for testing, or for manipulating other than the default home directory path.

### CODE REVIEW

**Comment by KevinSjoberg** [comment]
Thank you for taking the time to contribute to this project. I've done a quick code review and it looks good to me. Unless @dbrady has something to add, I'll merge it. 👍 🙂

**Comment by KevinSjoberg** [comment]
@dkowis could I recommend reformatting the commit messages to be more inline with how one usually structure them. See https://chris.beams.io/posts/git-commit/ for details.

**Comment by dkowis** [comment]
@KevinSjoberg How's that look?

**Comment by KevinSjoberg** [comment]
@dkowis much better. For consistency, you might want to change the commit saying "Making" into "Make". Great job nevertheless. 👍

**Comment by dkowis** [comment]
Did that, and changed the title of the pull request to make more sense. Thanks for the feedback!

**Comment by KevinSjoberg** [comment]
@dkowis thank you!

**Pull request merged**
